### ISSUE TITLE
remix.init script failed

### ISSUE THREAD

**Issue by crowne** [rphlmr/supa-fly-stack#79]
I tried to use the supa-fly-stack template but it failed with the message shown below.  
I'm running on Windows 10
npx --version = 10.2.5
node --version = v20.10.0

```shell
> npx create-remix --template rphlmr/supa-fly-stack
 remix   v2.4.0 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./appname

      ◼  Template: Using rphlmr/supa-fly-stack...
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with npm?
         Yes

  init   This template has a remix.init script. Do you want to run it?
         Yes

 ██████  Dependencies installing with npm...

      ▲  Oh no! Failed to install dependencies.
```

if I cd into the app-dir and run npm install I get the following output

```shell
› npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: appname@undefined
npm ERR! Found: @remix-run/react@2.4.0
npm ERR! node_modules/@remix-run/react
npm ERR!   @remix-run/react@"^2.4.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @remix-run/react@"^1.0.0" from remix-i18next@4.2.0
npm ERR! node_modules/remix-i18next
npm ERR!   remix-i18next@"^4.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\user.name\AppData\Local\npm-cache\_logs\2023-12-21T10_52_51_177Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\user.name\AppData\Local\npm-cache\_logs\2023-12-21T10_52_51_177Z-debug-0.log
```

**Comment by rphlmr** [comment]
Thanks for reporting this.

Will look at it, maybe similar to https://github.com/rphlmr/supa-stripe-stack/issues/14#issuecomment-1865885492

**Comment by rphlmr** [comment]
@crowne Can you try again 😇 ?
I let you close the issue if it's ok.

**Comment by crowne** [comment]
@rphlmr thanks that looks like the dependency issue is fixed, however there is a new error when running the remix.init script.

```shell
> npx create-remix --template rphlmr/supa-fly-stack

 remix   v2.4.0 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./appname

      ◼  Template: Using rphlmr/supa-fly-stack...
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with npm?
         Yes

  init   This template has a remix.init script. Do you want to run it?
         Yes

      ✔  Dependencies installed

      ✔  Git initialized
      ✔  Dependencies for remix.init script installed

      ◼  Running template's remix.init script...

🚀  Making something cool with this template ...

      ▲  Oh no! Template's remix.init script failed
```

**Comment by wizco47** [comment]
Ok, I'll try to set up a Windows VM to test asap.

**Comment by rphlmr** [comment]
Ok, I'll try to set up a Windows VM to test asap.

**Comment by crowne** [comment]
if I run npx remix init inside the app directory I see this:

```shell
 npx remix init
🚀  Making something cool with this template ...
Error: 🚨 Oops, remix.init failed

😌  Sorry, this template only supports TypeScript
    at main (C:\github\orgname\appname\remix.init\index.js:22:9)
    at Object.init (C:\github\orgname\appname\node_modules\@remix-run\dev\dist\cli\commands.js:102:11)
    at async Object.run (C:\github\orgname\appname\node_modules\@remix-run\dev\dist\cli\run.js:167:7)
```

**Comment by rphlmr** [comment]
Looks like something has changed 😬.
I come back soon, but `init` is not required. All it does is changing app name.

**Comment by seve** [comment]
Still seeing this, would recommend changing the issue name to reflect the new issue.

**Comment by mattwoberts** [comment]
I'm also getting this on a mac.

**Comment by rphlmr** [comment]
Hello,

Is it `remix.init script failed` for everyone here?
